version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_rochwin
    command:
      -p 5432
    expose:
      - 5432
    env_file:
      - config/.env

  app:
    build: .
    env_file:
      - config/.env
    container_name: rochwin
    volumes:
      - .:/rochwintest
    ports:
      - 7777:7777
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"

