# Generated by Django 4.2.7 on 2023-11-13 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 11, 30, 29, 13194, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Общая цена'),
        ),
    ]
